language : php
php :
  - "7.0"
  - "7.1"
  - "7.2"

before_script :
  - composer self-update
  - composer install

script :
    - mkdir -p build/logs
    - ./vendor/bin/phpunit

after_success:
    - travis_retry ./vendor/bin/php-coveralls -v

cache :
  directories :
    - vendor

notifications :
  on_success : never
  on_failure : never
